export const ACTIONS = {
  RESERVE_ROOM: 'RESERVE_ROOM',
  REGISTRATION_USER: 'REGISTRATION_USER',
  LOGIN_USER: 'LOGIN_USER',
  SET_USER: 'SET_USER',
  DEFINE_USER: 'DEFINE_USER',
  LOGOUT_USER: 'LOGOUT_USER',
};
