export const ACTIONS = {
  RESERVE_ROOM: 'RESERVE_ROOM',
  REGISTRATION_USER: 'REGISTRATION_USER',
  LOGIN_USER: 'LOGIN_USER',
  SET_USER: 'SET_USER',
  DEFINE_USER: 'DEFINE_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_USER_ERROR: 'SET_USER_ERROR',
  REGISTRATION_USER_SUCCES: 'REGISTRATION_USER_SUCCES',
  CLEAN_AUTH_ERROR_MESSAGE: 'CLEAN_AUTH_ERROR_MESSAGE',
  RESERVE_INSTRUMENT: 'RESERVE_INSTRUMENT',
};
