export const ACTIONS = {
  RESERVE_ROOM: 'RESERVE_ROOM',
  RESERVE_ROOM_SUCCES: 'RESERVE_ROOM_SUCCES',
  REGISTRATION_USER: 'REGISTRATION_USER',
  LOGIN_USER: 'LOGIN_USER',
  SET_USER: 'SET_USER',
  DEFINE_USER: 'DEFINE_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_USER_ERROR: 'SET_USER_ERROR',
  REGISTRATION_USER_SUCCES: 'REGISTRATION_USER_SUCCES',
  CLEAN_AUTH_ERROR_MESSAGE: 'CLEAN_AUTH_ERROR_MESSAGE',
  ADD_ORDER_IN_USER: 'ADD_ORDER_IN_USER',
  CANCEL_ORDER_IN_USER: 'CANCEL_ORDER_IN_USER',
  CANCEL_ORDER_IN_USER_SUCCES: 'CANCEL_ORDER_IN_USER_SUCCES',
  GET_ROOMS: 'GET_ROOMS',
  GET_ROOMS_SUCCES: 'GET_ROOMS_SUCCES',
  GET_DAY_IN_ROOM: 'GET_DAY_IN_ROOM',
  GET_DAY_IN_ROOM_SUCCES: 'GET_DAY_IN_ROOM_SUCCES',
  CLEAR_CHOSEN_DAY: 'CLEAR_CHOSEN_DAY',
  SET_RESERVE_ROOM_ERROR: 'SET_RESERVE_ROOM_ERROR',
  CLEAR_ROOM_SERVER_STATUS: 'CLEAR_ROOM_SERVER_STATUS',
  GET_RECORDS_SUCCES: 'GET_RECORDS_SUCCES',
  GET_RECORDS: 'GET_RECORDS',
  GET_DAY_IN_RECORD_SUCCES: 'GET_DAY_IN_RECORD_SUCCES',
  GET_DAY_IN_RECORD: 'GET_DAY_IN_RECORD',
  RESERVE_RECORD: 'RESERVE_RECORD',
  RESERVE_RECORD_SUCCES: 'RESERVE_RECORD_SUCCES',
  SET_RESERVE_RECORDS_ERROR: 'SET_RESERVE_RECORDS_ERROR',
  CLEAR_RECORD_SERVER_STATUS: 'CLEAR_RECORD_SERVER_STATUS',
  GET_USER_ORDERS: 'GET_USER_ORDERS',
  GET_USER_ORDERS_SUCCES: 'GET_USER_ORDERS_SUCCES',
  DELL_ORDER_IN_USER: 'DELL_ORDER_IN_USER',
  RESERVE_ROOM_CANCEL: 'RESERVE_ROOM_CANCEL',
  RESERVE_RECORD_CANCEL: 'RESERVE_RECORD_CANCEL',
  GET_ALL_ORDERS: 'GET_ALL_ORDERS',
  GET_ALL_ORDERS_SUCCES: 'GET_ALL_ORDERS_SUCCES',
};

export const GET_INSTRUMENTS = 'GET_INSTRUMENTS';
export const GET_INSTRUMENTS_SUCCES = 'GET_INSTRUMENTS_SUCCES';
export const GET_CHOSEN_DAY_INSTRUMENT = 'GET_CHOSEN_DAY_INSTRUMENT';
export const GET_CHOSEN_DAY_INSTRUMENTS_SUCCES =
  'GET_CHOSEN_DAY_INSTRUMENTS_SUCCES';
export const RESERVE_INSTRUMENT = 'RESERVE_INSTRUMENT';
export const RESERVE_INSTRUMENT_SUCCES = 'RESERVE_INSTRUMENT_SUCCES';
export const SET_RESERVE_INSTRUMENTS_ERROR = 'SET_RESERVE_INSTRUMENTS_ERROR';
export const CLEAR_INSTRUMENT_SERVER_STATUS = 'CLEAR_INSTRUMENT_SERVER_STATUS';
export const CLEAR_CHOSEN_DAY_INSTRUMENT = 'CLEAR_CHOSEN_DAY_INSTRUMENT';
